### ISSUE TITLE
Loading screen stuck at 0% after reconnecting.

### ISSUE THREAD

**Issue by Syntasu** [Syntasu/synn-loadscreen#1]
The progressbar will not update after disconnecting and reconnecting. It seems like the handlers in the javascript (progressbar-handler.js) seems to no longer receive any information.

This might be caused because the loading screen gets initialized after the events have been dispacted.

Repro:

1) Join server
2) Disconnect
3) Reconnect
4) Observe that the loading screen stays at 0%

<hr>

Seems like this also happens to the INIT_CORE event, In the client log you can clearly see it load before the loading screen.

**Comment by heyzred** [comment]
Dont think this has anything to do with the loading screen you've made. 
When i connect to any fivem server i ussually crash and when that happens i try to reconnect but the loading screen is freezing and i have to restart fivem. 

As i said. i don't think there is a problem with the loading screen but rather the FiveM application that fucks up after a crash or a disconnect :))

**Comment by Syntasu** [comment]
I am aware, but it's still an issue!

**Comment by ElPumpo** [comment]
Notice how the default loading screen doesn't provide a progress bar either on a reconnect..

**Comment by Syntasu** [comment]
Hmm, looks like we need to implement another approach for reconnects, loading in from start will need 5 stages (INIT_CORE, BEFORE_MAP, MAP, AFTER_MAP and INIT_SESSION). When reconnecting, only INIT_SESSION events are received, which seems logical since the main stuff is already loaded in.

I don't think this is due to a race condition, even though this seems to occur,  I think it will send the events regardless if the loading screen is ready/loaded or not.
